
export const QWEATHER_API_KEY = 'xxx';//改成你的apikey

// 你也可以把和风天气的 API 地址也定义在这里
export const QWEATHER_NOW_URL = 'https://xxx（你的API host）/v7/weather/now';

// 未来三天的天气预报
export const QWEATHER_3D_URL = 'https://xxx（你的API host）/v7/weather/3d';

// 未来七天的天气预报
export const QWEATHER_7D_URL = 'https://xxx（你的API host）/v7/weather/7d';
// 城市搜索的api
export const QWEATHER_CITY_LOOKUP_URL = 'https://xxx（你的API host）/geo/v2/city/lookup';
//逐小时天气的api
export const QWEATHER_24H_URL = 'https://xxx（你的API host）/v7/weather/24h';
//空气质量的api
export const QWEATHER_AIR_NOW_URL = 'https://xxx（你的API host）/v7/air/now';
//生活指数的api
export const QWEATHER_INDICES_1D_URL = 'https://xxx（你的API host）/v7/indices/1d';
