
export const QWEATHER_API_KEY = '67698b2f6f794ab0a8dd50882c7d9c74';

// 你也可以把和风天气的 API 地址也定义在这里
export const QWEATHER_NOW_URL = 'https://m8759fctv8.re.qweatherapi.com/v7/weather/now';

// 未来三天的天气预报
export const QWEATHER_3D_URL = 'https://m8759fctv8.re.qweatherapi.com/v7/weather/3d';

// 未来七天的天气预报
export const QWEATHER_7D_URL = 'https://m8759fctv8.re.qweatherapi.com/v7/weather/7d';
// 城市搜索的api
export const QWEATHER_CITY_LOOKUP_URL = 'https://m8759fctv8.re.qweatherapi.com/geo/v2/city/lookup';